### ISSUE TITLE
Ordenar los archivos 

### ISSUE THREAD

**Issue by duvanjamid** [jorgeruedaes/CopaAmistad#11]
Bueno muchachos ( @lizethrs and @jorgeruedaes  ) me da mucha pena chismosearles el proyecto :see_no_evil: , solo lo vi, chismosee, esa es la parte mala, ahora viene la parte buena: les voy a dar un consejo, pues para que esto les sea sostenible en el tiempo,

:octocat:  organizar la estructura del proyecto :exclamation: cuando vi todas esas carpetas y archivos quede :scream: 

ejemplo: se que tienen plugins, js ,css, images y los archivos php 

en un proyecto se recomienda estructurar la aplicacion de una forma similar a la siguiente

![c1aptura](https://cloud.githubusercontent.com/assets/3358485/7549049/ea4feb62-f5eb-11e4-94dc-a99749eb909a.png)

para hacer manejable tanto archivo de código

[aquí les dejo el enlace para que lean](https://geekytheory.com/estructura-de-un-proyecto-web/)

P.S. Tienen varios Incendios :fire:

**Comment by jorgeruedaes** [comment]
:) Gracias Duvan, vamos a organizar la estructura del proyecto,en realidad si esta muy desorganizado y tenemos que mejorarlo. 
P.S. Cualquier idea o comentario son gratamente recibidos  y puestos en practica.

**Comment by duvanjamid** [comment]
:+1:

**Comment by duvanjamid** [comment]
:ok_hand:
